name: ecomerce_design
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  eva_icons_flutter: ^2.0.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  carousel_slider: ^2.3.1
  http: ^0.12.2
  provider: ^4.3.2+2
  badges: ^1.1.4
  carousel_pro: ^1.0.0
  fancy_bottom_navigation: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/banner/ 
    - assets/products/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
      - family: popins
        fonts:
          - asset: fonts/Poppins-Regular.ttf
          - asset: fonts/Poppins-Italic.ttf
            style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


